<?php

namespace ConferenceBundle\Repository;

/**
 * EvaluateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluateRepository extends \Doctrine\ORM\EntityRepository
{
}
