<?php

namespace ConferenceBundle\Repository;

/**
 * ProgramComiteeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramComiteeRepository extends \Doctrine\ORM\EntityRepository
{
}
