<?php

namespace ConferenceBundle\Repository;

/**
 * ProposalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProposalRepository extends \Doctrine\ORM\EntityRepository
{
    public function addNewProposal($proposal){
        if ($proposal != null){
            $entityManager = $this->getEntityManager();
            $entityManager->persist($proposal);
            $entityManager->flush();
            return true;
        }
        throw new \Exception("Fatal Error");
    }
    public function persist($user)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($user);
        $entityManager->flush();
        return true;
    }
}
