<?php

namespace ConferenceBundle\Repository;

/**
 * SectionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionsRepository extends \Doctrine\ORM\EntityRepository
{
}
