<?php

namespace ConferenceBundle\Repository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $user
     * @return bool
     * @throws \Exception
     */
    public function addNewUser( $user)
    {
        if($user !=null)
        {
            $entityManager = $this->getEntityManager();
            $entityManager->persist($user);
            $entityManager->flush();
            return true;
        }
        throw new \Exception("Fatal Error");
    }
    public function persist($user)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($user);
        $entityManager->flush();
        return true;
    }

    /**
     * @param $email
     * @return array
     */
    public function getUserByEmail( $email)
    {
        return $this->findBy(['email'=>$email]);
    }

    /**
     * @param $id
     * @return array
     */
    public function getUserById( $id)
    {
        return $this->findBy(['id'=>$id]);
    }


}
