ConferenceBundle\Entity\ProgramComitee:
    type: entity
    table: null
    repositoryClass: ConferenceBundle\Repository\ProgramComiteeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
